workflows:
  ios-workflow:
    name: iOS Automatic Signing Workflow

    environment:
      xcode: latest
      cocoapods: default
      vars:
        # Replace this with your actual bundle identifier
        BUNDLE_IDENTIFIER: com.michaelverette.myapp

    scripts:
      - name: Install dependencies
        script: |
          if [ -f "Podfile" ]; then
            echo "Podfile found. Installing CocoaPods..."
            pod install --repo-update
          else
            echo "No Podfile found. Skipping CocoaPods installation."
          fi

      - name: Build iOS app
        script: |
          echo "Detecting build method..."
          WORKSPACE=$(find . -maxdepth 1 -name "*.xcworkspace" | head -n 1)
          PROJECT=$(find . -maxdepth 1 -name "*.xcodeproj" | head -n 1)

          echo "Detecting scheme..."
          if [ -n "$WORKSPACE" ]; then
            SCHEME=$(xcodebuild -workspace "$WORKSPACE" -list -json | jq -r '.workspace.schemes[0]')
            echo "Workspace found: $WORKSPACE"
            echo "Using scheme: $SCHEME"
            xcode-project build-ipa \
              --workspace "$WORKSPACE" \
              --scheme "$SCHEME" \
              --configuration "Release" \
              --automatic-signing
          elif [ -n "$PROJECT" ]; then
            SCHEME=$(xcodebuild -project "$PROJECT" -list -json | jq -r '.project.schemes[0]')
            echo "Project found: $PROJECT"
            echo "Using scheme: $SCHEME"
            xcode-project build-ipa \
              --project "$PROJECT" \
              --scheme "$SCHEME" \
              --configuration "Release" \
              --automatic-signing
          else
            echo "Error: No Xcode workspace or project found!"
            exit 1
          fi

    artifacts:
      - build/ios/ipa/*.ipa