workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      ios:
        xcode: latest
        cocoapods: default
        ios_signing:
          automatic_signing:
            enabled: true
            distribution_type: app-store
            bundle_identifier: com.michaelverette.myapp

    scripts:
      - name: Install dependencies
        script: |
          pod install

      - name: Build iOS app
        script: |
          xcode-project build-ipa \
            --workspace "MyApp.xcworkspace" \
            --scheme "MyApp" \
            --configuration "Release"
