workflows:
  ios-workflow:
    name: iOS Automatic Signing Workflow

    # Environment configuration
    environment:
      xcode: latest
      cocoapods: default
      vars:
        # Your app's bundle identifier
        BUNDLE_IDENTIFIER: com.michaelverette.myapp

    scripts:
      - name: Install dependencies
        script: |
          echo "Checking for Podfile..."
          if [ -f "ios/Podfile" ]; then
            echo "Podfile found. Installing CocoaPods..."
            cd ios
            pod install --repo-update
            cd ..
          else
            echo "No Podfile found. Skipping CocoaPods installation."
          fi

      - name: Build iOS app
        script: |
          echo "Detecting build method..."
          if [ -f "ios/*.xcworkspace" ] || [ -f "*.xcworkspace" ]; then
            WORKSPACE=$(find . -name "*.xcworkspace" | head -n 1)
            echo "Workspace found: $WORKSPACE"
            xcode-project build-ipa \
              --workspace "$WORKSPACE" \
              --scheme "MyApp" \
              --configuration "Release" \
              --automatic-signing
          elif [ -f "ios/*.xcodeproj" ] || [ -f "*.xcodeproj" ]; then
            PROJECT=$(find . -name "*.xcodeproj" | head -n 1)
            echo "Xcode project found: $PROJECT"
            xcode-project build-ipa \
              --project "$PROJECT" \
              --scheme "MyApp" \
              --configuration "Release" \
              --automatic-signing
          else
            echo "Error: No Xcode workspace or project found!"
            exit 1
          fi

    # Artifacts to export
    artifacts:
      - build/ios/ipa/*.ipa