workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      xcode: 15.4
      ios_signing:
        distribution_type: app_store   # ✅ corrected
        bundle_identifier: "com.example.GeoCards"
      vars:
        XCODE_PROJECT: "GeoCards.xcodeproj"
        XCODE_SCHEME: "GeoCards"
    scripts:
      - name: Install dependencies
        script: |
          brew install cocoapods || true
          pod install --project-directory=.
      - name: Build iOS app
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME" \
            --configuration Release \
            --automatic-signing
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - your-email@example.com