workflows:
  ios-workflow:
    name: iOS Automatic Signing Workflow

    # Environment configuration
    environment:
      xcode: latest
      cocoapods: default
      vars:
        # Your app's bundle identifier
        BUNDLE_IDENTIFIER: com.michaelverette.myapp

    # Scripts to run in order
    scripts:
      - name: Install dependencies
        script: |
          echo "Installing CocoaPods dependencies..."
          cd ios
          pod install --repo-update
          cd ..

      - name: Build iOS app
        script: |
          echo "Building IPA with automatic signing..."
          xcode-project build-ipa \
            --workspace "ios/MyApp.xcworkspace" \
            --scheme "MyApp" \
            --configuration "Release" \
            --automatic-signing

    # Artifacts to export
    artifacts:
      - build/ios/ipa/*.ipa